### ISSUE TITLE
Кросс-чек fancy-weather

### ISSUE THREAD

**Issue by bahnovak** [Hanna25/rsschool-cv#4]
Добрый день, хотелось бы узнать на каком разрешении у вас вёрстка сломалась, просто я все разрешения в хроме пробовал, ничего не ломалось . Плюс анимация микро и кнопки плей сделаны с помощью ключевых кадров .

**Comment by Hanna25** [comment]
Привет) написала в дискорде

пт, 5 июня 2020 г. в 10:40, bahnovak <notifications@github.com>:
